### ISSUE TITLE
`npm install` fail for the first time

### ISSUE THREAD

**Issue by alicoding** [mozilla/learning.mozilla.org#2345]
If you just cloned the project and tried to run `npm install` it fails on `cleanup` step.

```
> learning.mozilla.org@1.0.5 cleanup /Users/alialdallal/projects/learning.mozilla.org
> shx rm -rf build dist

/Users/alialdallal/projects/learning.mozilla.org/node_modules/shx/lib/shx.js:60
  Object.assign(_shelljs2.default.config, parsedArgs);
         ^
TypeError: undefined is not a function
    at shx (/Users/alialdallal/projects/learning.mozilla.org/node_modules/shx/lib/shx.js:60:10)
    at Object.<anonymous> (/Users/alialdallal/projects/learning.mozilla.org/node_modules/shx/lib/cli.js:6:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/alialdallal/.nvm/versions/node/v0.12.7/bin/node" "/Users/alialdallal/.nvm/versions/node/v0.12.7/bin/npm" "run" "cleanup"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! learning.mozilla.org@1.0.5 cleanup: `shx rm -rf build dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the learning.mozilla.org@1.0.5 cleanup script 'shx rm -rf build dist'.
npm ERR! This is most likely a problem with the learning.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     shx rm -rf build dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls learning.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alialdallal/projects/learning.mozilla.org/npm-debug.log
ERROR: "cleanup" exited with 1.
```

It seems like `shx` can't remove non-existing directory gracefully `shx rm -rf build dist`

**Comment by Pomax** [comment]
Hm, can you try with `cleanup` set to `shx --silent rm -rf build dist`?

**Comment by alicoding** [comment]
```
➜  learning.mozilla.org git:(master) shx --silent rm -rf build dist
/Users/alialdallal/.nvm/versions/node/v0.12.7/lib/node_modules/shx/lib/shx.js:60
  Object.assign(_shelljs2.default.config, parsedArgs);
         ^
TypeError: undefined is not a function
    at shx (/Users/alialdallal/.nvm/versions/node/v0.12.7/lib/node_modules/shx/lib/shx.js:60:10)
    at Object.<anonymous> (/Users/alialdallal/.nvm/versions/node/v0.12.7/lib/node_modules/shx/lib/cli.js:6:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by Pomax** [comment]
Interesting, so Object.assign is literally not part of node's API... which version of Node is this?

**Comment by alicoding** [comment]
Hahaha good catch @Pomax ! I totally forgot to switch back after working on node v0.12.7 >.< This is not an issue then! Derp :P
